newIssueWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to Project Zone!ğŸš€âš¡
  
  
  Thank you and congratsğŸ‰ for opening your very first issue in this project.
  

newPRWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome Project Zone!ğŸ’–
  
  
  Thank you and congratsğŸ‰ for opening your first pull request. We will get back to you as soon as we can ğŸ˜„.
  

firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ All the best for your amazing open source journey ahead ğŸš€.
