newIssueWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to Project Zone!ğŸš€âš¡
  
  Project-Zone is a web-app which suggests the user about the projects they can create based on their skills.âœ¨
  
  Thank you and congratulationsğŸ‰ for opening your very first issue in this project.
  Please make sure not to start working on the issue, unless you get assigned to it.ğŸ˜ƒ
  
  

newPRWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to Project Zone!ğŸ’–
  
  Project-Zone is a web-app which suggests the user about the projects they can create based on their skills.âœ¨
  
  Thank you and congratulationsğŸ‰ for opening your first pull request. We will get back to you as soon as we can.ğŸ˜ƒ
  

firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ All the best for your amazing open source journey ahead ğŸš€.
